### ISSUE TITLE
Dependency conflict in flutter_form_bloc

### ISSUE THREAD

**Issue by SebastianJL** [GiancarloCode/form_bloc#154]
I have the following dependency block in my pubspec.yaml.
```yaml
dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.0.0
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  form_bloc: ^0.17.0
  flutter_form_bloc: ^0.15.1
```

When I run it I get the following error:
```bash
Because flutter_form_bloc 0.15.1 depends on form_bloc ^0.15.0 and no versions of flutter_form_bloc match >0.15.1 <0.16.0, flutter_form_bloc ^0.15.1 requires form_bloc ^0.15.0.
So, because study_planer depends on both form_bloc ^0.17.0 and flutter_form_bloc ^0.15.1, version solving failed.
pub get failed (1; So, because study_planer depends on both form_bloc ^0.17.0 and flutter_form_bloc ^0.15.1, version solving failed.)
```

The only way I can resolve the issue is by setting them all to any, but that resolves to `bloc` and `flutter_bloc` version 5.x.x
