### ISSUE TITLE
[issue] Should flutter_form_bloc dependency be native to form_bloc?

### ISSUE THREAD

**Issue by huang12zheng** [GiancarloCode/form_bloc#176]
```yaml
# /form_bloc/packages/flutter_form_bloc/pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  form_bloc: ^0.19.0 #<------
# form_bloc:
  #   path: ../form_bloc
```

can you tell me why?
