### ISSUE TITLE
how to use this repo from Git in flutter? 

### ISSUE THREAD

**Issue by fredwilliam** [GiancarloCode/form_bloc#284]
i see some things in issues that are resolved but not yet updated in pub.dev so i tried to use this git repo instead without success
can someone help me?
this is how i tried it 
 form_bloc:
    git:
      url: git://github.com/GiancarloCode/form_bloc/

**Comment by fredwilliam** [comment]
> ```yaml
>   form_bloc: 0.20.4
>   flutter_form_bloc: 0.20.4 
> ```

Thanks for the response. I have tried the mentioned and am getting the following error... 

Error on line 17, column 11: Invalid description in the "flutter_form_bloc" pubspec on the "form_bloc" dependency: "../form_bloc" is a relative path, but this isn't a local pubspec.
   ╷
17 │     path: ../form_bloc
   │           ^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)

**Comment by julek-kal** [comment]
Did you add this code below dependencies section?
```yaml
dependency_overrides:
  form_bloc: 
    git:
      url: https://github.com/GiancarloCode/form_bloc
      path: packages/form_bloc
  flutter_form_bloc:
    git:
      url: https://github.com/GiancarloCode/form_bloc
      path: packages/flutter_form_bloc
```
