### ISSUE TITLE
Support for intl: 0.19.0 to match with pinned version for Flutter Localization

### ISSUE THREAD

**Issue by danqulogy** [GiancarloCode/form_bloc#351]

**Comment by oengmengthong** [comment]
this pull request should be fixed

https://github.com/GiancarloCode/form_bloc/pull/353

**Comment by danqulogy** [comment]
> this pull request should be fixed
> 
> #353

It looks like he not is available to merge the pull request. You can use my fork in your project to get it working:

[https://github.com/danqulogy/form_bloc](https://github.com/danqulogy/form_bloc)

Add it to your pubspec.yaml
```
...
 flutter_form_bloc:
    git:
      url: https://github.com/danqulogy/form_bloc.git
      ref: master
      path: packages/flutter_form_bloc
 .....

```

**Comment by mghase** [comment]
It look like abandoned i have updated to the lates flutter sdk 3.5 
you kan use this fork 
 ```
 flutter_form_bloc:
    git:
      url: https://github.com/QKSoft/form_bloc.git
      path: packages/flutter_form_bloc
```

**Comment by vasilich6107** [comment]
This package does not seem to be supported 
Just a friendly reminder to migrate

https://github.com/GiancarloCode/form_bloc/pull/312#issuecomment-1164240179

**Comment by mghase** [comment]
It look like abandoned i have updated to the lates flutter sdk 4
you can use this fork

```
 flutter_form_bloc:
    #    path: ../form_bloc/packages/flutter_form_bloc
    git:
      url: https://github.com/QKSoft/form_bloc.git
      path: packages/flutter_form_bloc
```
